# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

'/nvim ?\w*/' = "ï‰½"
".pdf" = "ïœ¤"
"/node/" = "ï¹"
"/npm/" = "ï¹"
"/yarn/" = "ï¹"
"alacritty" = "ï„ "
"Anki" = "ï„½"
"calculator" = "ï—«"
"chrome" = "ï‰¨"
"Code" = "ï„¡"
"discord" = "ï„›"
"disk usage" = "ïŸ‰"
"file manager" = "ï¼"
"firefox" = "ï‰©"
"github" = "ï„“"
"gnome-font-viewer" = "ï€´"
"Google Chrome" = "ï‰¨"
"Google-chrome" = "ï‰¨"
"google" = "ï† "
"gthumb" = "ï€¾"
"gucharmap" = "ï€´"
"KeePassXC" = "ï‚„"
"krita" = "ï€¾"
"libreoffice calc" = "ïƒ"
"libreoffice writer" = "ïœ˜"
"libreoffice" = "ï£…"
"menu" = "ï¡œ"
"mpv" = "ïœª"
"music" = "ï€"
"nvim" = "îŸ…"
"obs" = "ï€½"
"private browsing" = "ïˆ›"
"rust" = "î¨"
"Slack" = "ï†˜"
"Spotify" = "ï†¼"
"Steam" = "ï†¶"
"transmission" = "ï€™"
"videostream" = "ï˜˜"
"vlc" = "ï€½"
"Volume Control" = "ï‡"
"zoom" = "ï‚˜"
[other]
"fallback_icon" = "ğŸ¤¨"
